algo = input('Insira algo: ')
print(type(algo))
print('isalnum: ', algo.isalnum)
print('isupper: ', algo.isupper)
print('isalpha: ', algo.isalpha)
print('isascii: ', algo.isascii)
print('isdecimal: ', algo.isdecimal)
print('isdigit: ', algo.isdigit)
print('isidentifier: ', algo.isidentifier)
print('islower: ', algo.islower)
print('isnumeric: ', algo.isnumeric)
print('isspace: ', algo.isspace)
print('istitle: ', algo.istitle)