algo = input('Insira algo: ')
print(type(algo))
print('Tudo número? ', algo.isalnum())
print('Está tudo maiúsculo? ', algo.isupper())
print('É alfabético? ', algo.isalpha())
print('É ASCII? ', algo.isascii())
print('É decimal? ', algo.isdecimal())
print('É um dígito? ', algo.isdigit())
print('É um identificador? ', algo.isidentifier())
print('Está tudo minúsculo? ', algo.islower())
print('É número? ', algo.isnumeric())
print('É só espaço? ', algo.isspace())
print('É um título? ', algo.istitle())